---
title: "Fit Exponential Decay Models to dispersal patterns of _Ascochyta_ conidia"
author: "A.H. Sparks"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(fig.width = 12, fig.height = 9) 
```

## Import Data

See "R/wrangle_raw_data.R" for the script that handles the data import. This
Rmd file focuses on the models themselves.

```{r libraries, message=FALSE, echo=FALSE}
library("tidyverse")
library("mgcv")
library("theme.usq")
library("broom")
library("skimr")
```

```{r import data, message=FALSE, echo=FALSE}
source("R/wrangle_raw_data.R")
```

## Fit Non-linear Model

```{r exponential}
ggplot(dat, aes(x = dist, y = mean_count_pot)) +
   geom_count() +
   stat_smooth(
      method = "nls",
      formula = y ~ SSasymp(x, Asym, R0, lrc),
      se = FALSE,
      colour = usq_cols("usq yellow")
   ) +
   ylab("Mean lesion count values") +
   xlab("Distance (m)") +
   theme_usq(base_size = 15)
```

```{r}
fit <- nls(mean_count_pot ~ SSasymp(dist, Asym, R0, lrc), data = dat)
summary(fit)
```