% About

The goal of this research is to examine the effects of _Phoma rabiei_ conidia on long distance dispersal of chickpea ascochyta blight in Australia.

## Project team

- Dr Ihsan Khaliq, University of Southern Queensland, Queensland

- Dr Paul Melloy, University of Southern Queensland, Queensland

- Daniel Burrell, University of Southern Queensland, Queensland

- Joshua Fanning, Agriculture Victoria, Victoria

- Jean Galloway, DPIRD, Western Australia

- Kevin Moore, NSW DPI, New South Wales

**Project PI:**

- Associate Professor Adam H. Sparks, University of Southern Queensland, Queensland

## Methodology

Considerations about sampling, study design, randomization, factors, response variables, etc.


## Citation

Please cite this research compendium as:  

> Authors, . Title of compendium. Online at https://doi.org/xxx/xxx

## Licences

Data: [CC-0](https://creativecommons.org/publicdomain/zero/1.0/) attribution requested in reuse
Manuscript: [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/)  
Code: [MIT](https://opensource.org/licenses/MIT) year: 2020, copyright holder: Adam H. Sparks

## Contributions

We welcome contributions from everyone.
Before you get started, please see our [contributor guidelines](CONTRIBUTING.html).
Please note that this project is released with a [Contributor Code of Conduct](CONDUCT.html).
By participating in this project you agree to abide by its terms.
