---
title: "Visualise Data"
author: "A.H. Sparks"
date: "`r Sys.Date()`"
output:
  html_document:
    number_sections: yes
    toc: yes
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width = 9.4, fig.height = 9.4)
```

```{r libraries, message=FALSE}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, lubridate, clifro, skimr, extrafont, ggpubr, here)

theme_set(theme_pubclean(base_size = 14))
```

```{r fonts, include=FALSE, message=FALSE, eval=FALSE}
# run only if knitting on new computer
# this is necessary to embed fonts in .eps files for EJPP
font_import(pattern = "Arial")
loadfonts(device = "postscript") 
```

```{r import_data, message=FALSE}
# import
lesion <- read_csv(here("cache", "summarised_lesion_data.csv")) %>%
   mutate(SpEv = ordered(factor(
      SpEv,
      levels = c(
         "Horsham Irrg 1",
         "Horsham Irrg 2",
         "Horsham Mixd 1",
         "Horsham Rain 1",
         "Horsham Rain 2",
         "Curyo Rain 1"
      )
   )))

weather <- read_csv(here("cache", "cleaned_weather.csv"))

dat <- left_join(lesion, weather, by = c("site", "rep"))

skim(dat)
```

## Visualise Counts per Pot

```{r lesion-count, fig.cap="Density plot of mean lesions counted per pot for all six events.", message=FALSE, warning=FALSE}
ggplot(lesion, aes(x = mean_pot_count)) +
   geom_density() +
   xlab("Mean lesion count per pot")
```

## Visualise the Dispersal Data

```{r combined-dispersal, message=FALSE, warning=FALSE, fig.cap="Mean counts of lesions per pot at each station for ten transects at each station for all six events."}
ggplot(lesion, aes(x = distance,
                y = mean_pot_count)) +
   geom_count() +
   stat_summary(fun.y = "median",
                geom = "line",
                na.rm = TRUE) +
   stat_summary(
      fun.y = "median",
      colour = "red",
      size = 2,
      geom = "point"
   ) +
   scale_x_continuous(breaks = c(0, 10, 25, 50, 75)) +
   ylim(c(-0.5, 9)) +
   ylab("Mean lesion count values") +
   xlab("Distance (m)") +
   facet_wrap(. ~ SpEv, ncol = 3)

# save a .png to refer to while writing and a .eps for publication submission
ggsave("figures/Fig2.png")
ggsave("figures/Fig2.eps")
embed_fonts("figures/Fig2.eps", outfile = "figures/Fig2.eps",
            options = "-dEPSCrop")
```

## Visualise the Rainfall and Irrigation Events

```{r rain, message=FALSE, warning=FALSE, fig.cap=paste0("Hourly precipitation for each of the six rainfall or irrigation events at two locations. Events are denoted by the location, 'Horsham' or 'Curyo'; source of precipitation 'Irrg' (irrigation), 'Rain' (rainfall) or 'Mixd' (both simultaneously); and event '1', '2' or '3.'")}

dat %>%
   group_by(SpEv) %>%
   mutate(Hour = floor_date(time, "1 hour")) %>%
   group_by(SpEv, Hour) %>%
   summarize(sum(rainfall)) %>%
   ggplot(aes(x = Hour, y = `sum(rainfall)`)) +
   geom_col() +
   scale_x_datetime(
      "Date (day-month)",
      date_breaks = "day",
      date_labels = "%d-%m",
      date_minor_breaks = "hour",
      guide = guide_axis(check.overlap = TRUE)
   ) +
   ylab("Precipitation (mm)") +
   facet_wrap(. ~ SpEv, ncol = 3, scales = "free_x")
```

## Visualise the Windspeed and Direction

```{r wind, message=FALSE, warning=FALSE, fig.cap=paste0("Windroses showing the windspeed and direction for each event. Events are denoted by the location, 'Horsham' or 'Curyo'; source of precipitation 'Irrg' (irrigation), 'Rain' (rainfall) or 'Mixd' (both simultaneously); and event '1', '2' or '3.'")}
pw <-
   with(
      dat,
      windrose(
         wind_speed,
         wind_direction,
         SpEv,
         n_col = 3,
         col_pal = "D",
         legend_title = "Wind speed (m/s)"
      )
   )
pw +
   xlab("") +
   theme_pubclean()

# save a .png to refer to while writing and a .eps for publication submission
ggsave("figures/Fig3.png")
ggsave("figures/Fig3.eps")
embed_fonts("figures/Fig3.eps", outfile = "figures/Fig3.eps",
            options = "-dEPSCrop")
```

## Heatmap of Lesions Along Transects

```{r polar_coord_transects, message = FALSE, warning=FALSE, fig.cap=paste0("Heatmap showing count of mean lesions per pot at each station along each of ten transects. Note that any stations where the mean count was zero for any event, the data are not shown for clarity. Events are denoted by the location, 'Horsham' or 'Curyo'; source of precipitation 'Irrg' (irrigation), 'Rain' (rainfall) or 'Mixd' (both simultaneously); and event '1', '2' or '3.'")}
heat_dat <-
   lesion %>%
   group_by(SpEv, degrees) %>%
   mutate(summed_count_pot =
             case_when(distance == 0 ~ sum(mean_pot_count),
                       TRUE ~ mean_pot_count)) %>% 
   filter(mean_pot_count > 0)

ggplot(data = heat_dat,
       aes(
          x = degrees,
          y = distance,
          colour = summed_count_pot,
          size = summed_count_pot
       )) +
   geom_count(data = subset(heat_dat, distance == 0)) +
   geom_count(data = subset(heat_dat, distance > 0)) +
   scale_colour_viridis_c(
      direction = -1,
      name = "n",
      guide = "legend"
   ) +
   coord_polar(theta = "x",
               start = 0,
               direction = 1) +
   scale_size(range = c(2, 8), name = "n") +
   scale_x_continuous(
      breaks = c(0, 90, 180, 270),
      expand = c(0, 0),
      limits = c(0, 360),
      labels = c("N", "E", "S", "W")
   ) +
   scale_y_continuous(breaks = c(0, 10, 20, 50, 75),
                      limits = c(0, 75)) +
   ylab("Distance (m)") +
   xlab("Transect") +
   facet_wrap(. ~ SpEv, ncol = 3)


ggsave("figures/Fig4.png")
ggsave("figures/Fig4.eps")
embed_fonts("figures/Fig4.eps", outfile = "figures/Fig4.eps",
            options = "-dEPSCrop")
```
